2025-07-04 11:03:02 - INFO - Application starting...
2025-07-04 13:03:15 - INFO - Application starting...
2025-07-04 13:03:25 - INFO - DNS scan started - Target: example.com, Wordlist: subdomains-top1000.txt, Types: ['A', 'AAAA', 'CNAME']
2025-07-04 13:03:25 - INFO - DNS scan completed - Target: example.com, Results: 1
2025-07-04 13:03:26 - INFO - Results exported to exports\scan_results_example.com_1751598206.json
2025-07-04 13:04:35 - INFO - Application starting...
2025-07-04 13:53:12 - INFO - Application starting...
2025-07-04 14:03:16 - INFO - Application starting...
2025-07-04 14:08:30 - INFO - Application starting...
2025-07-04 14:13:53 - INFO - Application starting...
2025-07-04 14:24:38 - INFO - Application starting...
2025-07-04 14:36:54 - INFO - Application starting...
2025-07-04 14:56:51 - INFO - Application starting...
2025-07-04 14:58:23 - ERROR - Unhandled exception:
Traceback (most recent call last):
  File "c:\Users\allie\Coding Projects\hackulator\app\pages\enumeration_page.py", line 1010, in toggle_scan
    self.run_ldap_scan()
    ~~~~~~~~~~~~~~~~~~^^
  File "c:\Users\allie\Coding Projects\hackulator\app\pages\enumeration_page.py", line 1144, in run_ldap_scan
    self.current_worker.signals.progress_start.connect(self.start_progress)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'LDAPWorkerSignals' object has no attribute 'progress_start'

2025-07-04 15:00:27 - INFO - Application starting...
2025-07-04 15:00:55 - ERROR - Unhandled exception:
Traceback (most recent call last):
  File "C:\Users\allie\Coding Projects\hackulator\app\pages\enumeration_page.py", line 1010, in toggle_scan
    self.run_ldap_scan()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\allie\Coding Projects\hackulator\app\pages\enumeration_page.py", line 1144, in run_ldap_scan
    self.current_worker.signals.progress_start.connect(self.start_progress)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'LDAPWorkerSignals' object has no attribute 'progress_start'

2025-07-04 15:01:36 - INFO - Application starting...
2025-07-04 15:25:29 - INFO - Application starting...
2025-07-04 15:33:06 - INFO - Application starting...
2025-07-04 15:40:05 - INFO - Application starting...
2025-07-04 15:48:22 - INFO - Application starting...
2025-07-04 15:49:21 - INFO - Application starting...
2025-07-04 15:49:31 - INFO - Application starting...
2025-07-04 15:59:55 - INFO - Application starting...
2025-07-04 16:12:53 - INFO - Application starting...
2025-07-04 16:13:18 - ERROR - Unhandled exception:
Traceback (most recent call last):
  File "c:\Users\allie\Coding Projects\hackulator\app\pages\enumeration_page.py", line 1351, in toggle_scan
    self.run_av_firewall_scan()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\Users\allie\Coding Projects\hackulator\app\pages\enumeration_page.py", line 1650, in run_av_firewall_scan
    self.current_worker.signals.progress_start.connect(self.start_progress)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AVFirewallWorkerSignals' object has no attribute 'progress_start'

2025-07-04 16:18:40 - INFO - Application starting...
2025-07-04 16:35:00 - INFO - Application starting...
2025-07-04 16:35:13 - ERROR - Unhandled exception:
Traceback (most recent call last):
  File "C:\Users\allie\Coding Projects\hackulator\app\pages\enumeration_page.py", line 1349, in toggle_scan
    self.run_ike_scan()
    ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\allie\Coding Projects\hackulator\app\pages\enumeration_page.py", line 1155, in run_ike_scan
    self.current_worker.signals.progress_start.connect(self.start_progress)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'IKEWorkerSignals' object has no attribute 'progress_start'

